#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PI 3.14159265358979323846

#define VENTANA_ANCHO 1000
#define VENTANA_ALTO 700

#define JUEGO_FPS 100

//defines nave y disparo
#define NAVE_ROTACION_PASO (PI/20)
#define NAVE_X_INICIAL (VENTANA_ANCHO/2)
#define NAVE_Y_INICIAL (VENTANA_ALTO/2)
#define NAVE_VX_INICIAL 0
#define NAVE_VY_INICIAL 0
#define NAVE_ANGULO_INICIAL (PI/2)
#define NAVE_POTENCIA_INICIAL 1
#define INCREMENTO_POTENCIA 1000
#define NAVE_MAX_POTENCIA 10000

#define TIEMPO_DISPARO_MAX 0.7

//
#define NOMBRE_SPRITE_NAVE "SHIP"
#define NOMBRE_SPRITE_CHORRO "THURST"
#define NOMBRE_SPRITE_AST_1 "ROCK1"
#define NOMBRE_SPRITE_AST_2 "ROCK2"
#define NOMBRE_SPRITE_AST_3 "ROCK3"
#define NOMBRE_SPRITE_AST_4 "ROCK4"
#define NOMBRE_SPRITE_DISPARO "SHOT"

//defines vidas
#define CANT_VIDAS_INICIAL 4
#define ANGULO_VIDAS PI/2
#define POS_X_VIDAS 100
#define POS_Y_VIDAS 645
#define OFFSET 11

//defines reduccion porcentual para el movimiento de la nave
#define REDUCCION_POTENCIA 0.1
#define REDUCCION_VELOCIDAD 0.01

//Defines asteroides
#define VELOCIDAD_MAX_ASTEROIDE 15
#define VELOCIDAD_MIN_ASTEROIDE 1
#define RADIO_MIN_ASTEROIDE 8
#define RADIO_MAX_ASTEROIDE 32
#define CANT_ASTEROIDES_SPRITE 4
#define CANT_ASTEROIDES_INICIAL 4
#define AUMENTO_CANT_ASTEROIDES 2
#define RADIO_AST_1 8
#define RADIO_AST_2 16
#define RADIO_AST_3 32

//defines graficador
#define ESCALA_DISPARO 3
#define ESCALA_NAVE 3
#define ESCALA_VIDAS 0.6

#endif // _CONFIG_H_

