#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PI 3.14159265358979323846

#define VENTANA_ANCHO 1000
#define VENTANA_ALTO 700

#define JUEGO_FPS 100

#define NAVE_ROTACION_PASO (PI/20)
#define NAVE_MAX_POTENCIA 15

#define NAVE_X_INICIAL (VENTANA_ANCHO/2)
#define NAVE_Y_INICIAL (VENTANA_ALTO/2)
#define NAVE_VX_INICIAL 10
#define NAVE_VY_INICIAL 10
#define NAVE_ANGULO_INICIAL 0
#define NAVE_POTENCIA_INICIAL 1

#define TIEMPO_DISPARO_MAX 1

#define NOMBRE_SPRITE_NAVE "SHIP"
#define NOMBRE_SPRITE_CHORRO "THURST"
#define NOMBRE_SPRITE_AST_1 "ROCK1"
#define NOMBRE_SPRITE_AST_2 "ROCK2"
#define NOMBRE_SPRITE_AST_3 "ROCK3"
#define NOMBRE_SPRITE_AST_4 "ROCK4"
#define NOMBRE_SPRITE_DISPARO "SHOT"

#define ESCALA_DISPARO 3
#define ESCALA_NAVE 3

#endif // _CONFIG_H_

